version: 2

before:
  hooks:
    - go mod tidy
    - go test

builds:
  - id: try
    binary: try
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: try
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
      - zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

upx:
  - enabled: true
    ids: [try]
    compress: best
    lzma: true
    brute: true
    goos: [linux, windows]  # Exclude darwin (macOS) due to compatibility issues

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  name_template: "v{{ .Version }}"